-- Migration number: 0002 	 2026-02-25T23:56:14.830Z
CREATE TABLE IF NOT EXISTS products (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	price REAL NOT NULL,
	stock INTEGER DEFAULT 0,
	category TEXT NOT NULL,
	images_json TEXT,
	description TEXT
); 

CREATE TABLE invoices (id INTEGER PRIMARY KEY AUTOINCREMENT,
product_id INTEGER NOT NULL,
total REAL NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
